### ISSUE TITLE
Modificar emoji de HomePage

### ISSUE THREAD

**Issue by thomaspufahl** [colidevs/com-dirusoft#2]
### Modificar emoji

Cambiar emoji de mano en el `<Button/>` de la HomePage 
👋 => 🚀🚀🚀

Actualmente:
![Image](https://github.com/thomaspufahl/com-dirusoft/assets/104370730/4d90b14b-595b-4ef3-bd2f-035a271355ad)

Cambio esperado:
![Image](https://github.com/thomaspufahl/com-dirusoft/assets/104370730/aa5fdd94-c834-4691-b7ee-6302355f318e)

**Comment by louisv20** [comment]
¿Puedo ayudar con esta modificación?
